### ISSUE TITLE
Cannot import into jidoujisho

### ISSUE THREAD

**Issue by Dollique** [stephenmk/Jitendex#107]
I am not sure if this is an issue with jidoujisho or jitendex.
I am not able to import any version of the jitendex into jidoujisho
Note: The import of JMdict worked, so I guessed it is probably an issue with jitendex.

I get this error message:
`PathNotFoundException: Cannot open file, path = '/data/user/0/app.lrorpilla.yuuna/app_flutter/dictionaryImportWorkingDirectory/index.json' (OS Error: No such file or directory, errno = 2)`

I tried versions 4.7, 4.6, 4.5 and 3.2-1

Some addition info:
- Device: ereader mobiscribe Wave
- CPU: ARM Cortex-A53 processor
- App: jidoujisho_yuuna_2.8.9-armeabi.apk

Screeenshot:
![20240927_102501](https://github.com/user-attachments/assets/d680127b-bdc8-4259-a030-087f66a7cad4)

**Comment by stephenmk** [comment]
https://github.com/arianneorpilla/jidoujisho?tab=readme-ov-file#-supported-formats

> Users may import [Yomichan](https://foosoft.net/projects/yomichan/) dictionaries for Japanese, [some can be found here](https://drive.google.com/drive/folders/1tTdLppnqMfVC5otPlX_cs4ixlIgjv_lH). Note that Yomichan dictionaries using structured-content are currently unsupported.

https://github.com/arianneorpilla/jidoujisho/issues/374

> Please add Jitendex (https://jitendex.org/) support, it's a better JMdict version.

https://github.com/arianneorpilla/jidoujisho/pull/389

> This PR tries to support the latest V3 dict schema provided by Yomitan, with a focus on rendering Jitendex's dictionary entries nicely (see pics).

---

The problem is with jidoujisho. There's nothing I can do, sorry.
