### ISSUE TITLE
Failure on import to Yomitan

### ISSUE THREAD

**Issue by Goluxas** [stephenmk/Jitendex#109]
I got the following error in both the Firefox and Chromium (via Yomininja) versions of Yomitan. It passes the Validation step but errors shortly after. I can't tell if it's the formatting step or the one after because it moves so quickly. I redownloaded the dictionary to make sure it wasn't a download error.

Error: Could not determine media type for image at path "jitendex/graphics/da94142fe53d96f1a4b512920bd41366.avif" for アメリカンショートヘア (アメリカンショートヘア) in Jitendex.org [2024-09-29]

**Comment by stephenmk** [comment]
You should to check to make sure you're not using an old version of Yomitan. Support for `avif` image files was added in Yomitan [24.9.9.0](https://github.com/themoeway/yomitan/releases/tag/24.9.9.0), and the latest version of Yomitan is [24.9.16.0](https://github.com/themoeway/yomitan/releases/tag/24.9.16.0). So I was hoping that browsers would have automatically updated it for everyone by now.

**Comment by Goluxas** [comment]
Perfect! Issue is solved. I was running a 24.7 version. Steps to fix below in case anyone else has this problem.

### Firefox

It seems like Firefox did not update my extensions by default, though it's possible I chose that in the past and forgot.

Extensions > Manage Extensions > Gear Icon > Check for Updates

### YomiNinja

Download yomitan-chrome.zip from the releases page of the Yomitan repo.

In YomiNinja: Extensions Icon > Install (Zip). Restart YomiNinja. You do not have to uninstall the old version first. Your settings for Yomitan will carry over.
