### ISSUE TITLE
Prevent double-clicks from selecting text of neighboring glosses

### ISSUE THREAD

**Issue by dududkrn** [stephenmk/Jitendex#122]
Hi there. I am not good at English, so I search Japanese words and using GoldenDict, at the same time I will choose and search the English words in the Jitendex.org dictionary.
When I double click
![image](https://github.com/user-attachments/assets/f5f8e9e0-b4d4-4e5e-bd78-5c67a0bddfe2)
trouble ; bother
I want to choose "bother", but it will be "trouble ; bother"
So I hope that the ; can really separate the words so that I can using double click to choose every words
![image](https://github.com/user-attachments/assets/87038461-af14-4ef3-be27-badd0916540b)

**Comment by stephenmk** [comment]
I just published [an updated version of the dictionary](https://jitendex.org/pages/downloads.html) which does not have this problem. Please give it a try.

**Comment by stephenmk** [comment]
No response, but I think this is fixed.

**Comment by dududkrn** [comment]
> [Dec 19, 2024](#event-15711128862)
Thank you thank you so much~! Wonderful. Beautiful!
It is very very good now.
