### ISSUE TITLE
Yomitan: add JMdict entry ID as possible value for Anki cards

### ISSUE THREAD

**Issue by fieira** [stephenmk/Jitendex#125]
the [kanji study app](https://mindtwisted.com) for android uses the JMdict ID for anki cards that link back to their entries on the app. Having the ID as a possible value in yomitan would allow for creating the same type of card, making for a more seamless experience between systems.

![Imagem do WhatsApp de 2024-12-26 à(s) 08 10 16_5732f5ef](https://github.com/user-attachments/assets/81dd1b90-0f3c-46b2-a1d5-7de462dd3387)
![Imagem do WhatsApp de 2024-12-26 à(s) 08 10 16_2d1625ac](https://github.com/user-attachments/assets/fdc7906e-f7f4-4e7f-be08-bfdd99582f58)

**Comment by stephenmk** [comment]
The JMdict IDs are already included within the jitendex dictionary data. Yomitan doesn't currently have the ability to export this information to flashcards. In any case, there's nothing I can do. This feature would need to be implemented by the people who develop Yomitan.

**Comment by fieira** [comment]
thanks for the feedback, ill see what i can do with yomitan rn then
