### ISSUE TITLE
Yomichan dictionary name doesn't allow for css styling

### ISSUE THREAD

**Issue by cademcniven** [stephenmk/Jitendex#2]
In yomichan if you want to style dictionaries individually you have to qualify the selector with the dictionary name.

```html
<li class="definition-item" data-dictionary="Jitendex [2023-10-12]" data-index="0">
```

The issue is that the dictionary name contains the release date of the dictionary (which will obviously change), so the css would break on future releases. This isn't a huge deal for just me, but if I wanted to share my css with others, I'd have to also ensure they're always on the exact same version as me.

This issue also extends into anki, because in complex dictionaries like this, extra css on your anki note type can be needed to make everything look correct on your cards. This would mean that for every release of the dictionary people would have to duplicate the css to apply to cards made with the new dictionary version.

**Comment by stephenmk** [comment]
You can use some special [attribute selector syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors) to select attributes that begin with the string "Jitendex"

```css
li[data-dictionary^="Jitendex"] {
  /* your styles go here */
}
```

> This isn't a huge deal for just me, but if I wanted to share my css with others, I'd have to also ensure they're always on the exact same version as me.

I do appreciate the thoughtful feedback. Feel free to let me know if you notice any other details like this that you think can be improved.
