### ISSUE TITLE
Error when trying to import into Yomitan

### ISSUE THREAD

**Issue by krischimk** [stephenmk/Jitendex#44]
Only with the new v.4.0-1
Error message:
Error: Dictionary has invalid data in '0'
<img width="929" alt="image" src="https://github.com/stephenmk/Jitendex/assets/121830124/76751b83-1f27-4122-b449-32daeefa6a4c">

**Comment by stephenmk** [comment]
The new dictionary only supports version 23.12.29.0 of Yomitan. You can check your version number by clicking on that "About Yomitan" button in the lower left corner. You may need to tell your browser to go fetch the latest version.

**Comment by krischimk** [comment]
Worked, now that Yomitan is updated. 👍

**Comment by stephenmk** [comment]
Glad to hear it. I'll leave this issue open for a while so that others can see it.

**Comment by stephenmk** [comment]
Hopefully everyone has received the update to the latest version of Yomitan by now. I'll close this issue.
