### ISSUE TITLE
Make all tags clickable

### ISSUE THREAD

**Issue by Aridow** [stephenmk/Jitendex#59]
Some tags in Jitendex behave as in the original JMdict, but others are not clickable, as in this screenshot.
![image](https://github.com/stephenmk/Jitendex/assets/65539338/20927a2e-3f2c-438c-89c6-acea5b4756ca)
Unless it's too much to make, I think If all tags behaved as in JMdict, the tooltip would display faster, they would keep displaying even when moving the cursor away, and it would allow for copy-paste. I don't know if there is a way to do this with css.

**Comment by stephenmk** [comment]
I agree and I would like to be able to add this functionality. Unfortunately it is not currently possible to include clickable tags within the the bodies of dictionary entries. Support for this feature would need to be added to the Yomitan browser extension.

I will ask the Yomitan developers if they can add this ability.

**Comment by RyanOrigens** [comment]
@stephenmk Can't you just hide this information in the dictionary, add it as a tag and and unhide it on anki only? 

For example if you hide any information on CSS (https://github.com/stephenmk/Jitendex/wiki/Custom-Styles-in-Yomitan#highlighting-the-example-keyword), it will still be going to anki!

**Comment by stephenmk** [comment]
I opened an issue for this feature in the Yomitan repo. There's currently nothing I can do with the dictionary file to resolve this issue, so I am closing it.
