### ISSUE TITLE
Re-add data attributes

### ISSUE THREAD

**Issue by parfait8566** [stephenmk/Jitendex#6]
Unless it's too much work, I'd really appreciate a version with all the data attributes (like your previous JMdict Extra) as it makes it much easier to customize the dictionary on Yomichan/Anki

**Comment by stephenmk** [comment]
In principle I don't have a problem with having this sort of metadata in the document markup. If you look at the MDict (MDX) version of Jitendex, you'll find that almost all of the elements have been assigned `class` attributes.

From a technical point of view, the only problem with adding this information to the Yomichan version is that it increases the filesize and the validation time (although perhaps not by much for either one).

From a design point of view, I have some issues with this. This project is still very young, and the design is not set in stone. I can't guarantee that these metadata tags will be applicable in all future versions of Jitendex. I think it's a bad idea for anyone to spend time making customizations based upon the current structure of the dictionary.

If you have some specific design suggestions that could potentially improve the dictionary, I'd be happy to consider them. Without a compelling reason for adding more metadata tags, I'd rather spend my time working on features that I know will be useful for users instead.

**Comment by parfait8566** [comment]
> I guess I can add attributes for the parts that you mentioned (references, antonyms, and forms).

Thanks. Could you add attributes for `infoGlossary` as well?

> If you agree not to yell at me when the dictionary updates and all of your customizations break

Absolutely! 🙂
I really appreciate your work.

**Comment by stephenmk** [comment]
Okay, the [the new version](https://github.com/stephenmk/Jitendex/releases/latest) should have everything you need
