### ISSUE TITLE
Circles Are Ovally When the Display Font Is Changed

### ISSUE THREAD

**Issue by MarvNC** [stephenmk/Jitendex#61]
Original chart:
![chrome_Yomitan_Search_-_発条_-_Yomitan_Search_2024-01-19_22-27-54](https://github.com/stephenmk/Jitendex/assets/17340496/fedb023b-8afc-4a6d-89b0-89ae821ed23f)
After applying css:
```css
* {
  font-family: 'Noto Sans JP', sans-serif;
}
```
![chrome_Yomitan_Search_-_発条_-_Yomitan_Search_2024-01-19_22-27-33](https://github.com/stephenmk/Jitendex/assets/17340496/36b693e8-cd40-42ab-a8c9-e559d193476a)

Of course this is a really minor issue and I have no idea how it could be fixed, just wanted to bring this to your attention if you weren't already aware. Feel free to close if not feasible.

**Comment by stephenmk** [comment]
> just wanted to bring this to your attention if you weren't already aware.

Thanks. Yes, I've already spent some time pulling my hair out over it. I guess since it's the font, I'd need to find some way to draw the circle that doesn't involve the text.

I'll leave this issue open since this really is something I need to fix.

**Comment by stephenmk** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path

I can replace most of the `padding` and `border-radius` style stuff I'm doing with a simple `clip-path: circle()` style to get the effect that I want. I'll have to submit another tiny patch to yomitan to add support for it.

![circle](https://github.com/stephenmk/Jitendex/assets/8003332/14b68657-7933-45d9-bf38-4cf3ec2349b0)

**Comment by starxeras** [comment]
Is this still being worked on? I know it's a minor thing, but it sometimes really bugs me lol

**Comment by MarvNC** [comment]
Waiting on the SC changes to be released to Yomitan stable, likely.

**Comment by stephenmk** [comment]
The patch that I submitted to Yomitan in January (described and linked above) was released in a new stable version on [April 14](https://addons.mozilla.org/en-US/firefox/addon/yomitan/versions/).

Starting with version 4.7, new releases of Jitendex for Yomitan should not have this problem.
