### ISSUE TITLE
Show rarely-used/irregular forms right away

### ISSUE THREAD

**Issue by parfait8566** [stephenmk/Jitendex#62]
You often encounter "rare" or "irregular" forms when reading novels, manga, etc. and it can get a bit annoying to click to the more common forms every time to see the definitions. It's also a bit annoying when you'd like to compare the English glosses to the ones used by monolingual dictionaries for the rare forms.
I understand that for beginners this approach might actually be more useful as they're guided to the forms they're more likely to encounter. But I still think it'd be useful to show them right away for more advanced learners.
Would it be possible to hide by default the definitions for rare/irregular forms using CSS magic and then let advanced learners forcefully enable them using custom CSS?

**Comment by stephenmk** [comment]
I've [said in the past](https://github.com/stephenmk/Jitendex/issues/8#issuecomment-1779963577) that I can't make accommodations for users who can't conveniently type, scroll, or click in their dictionary client. That's a problem for those users to solve. Personally, in the past I have bound macros to a game controller connected to my PC to make it more convenient to swap between windows and navigate dictionaries without needing to switch to a keyboard and mouse.

> Would it be possible to hide by default the definitions for rare/irregular forms using CSS magic and then let advanced learners forcefully enable them using custom CSS?

This will be possible if support for the `display` attribute is added to Yomitan. I don't know how they would feel about adding that attribute or if there's enough of a demand to justify adding it.

I built a [version of Jitendex for Yomitan](https://github.com/stephenmk/Jitendex/releases/tag/v4.1s) for you which displays the full entries for rare/outdated/irregular terms. Let me know if you ever want a newer version with the latest data and I can build it again.
