### ISSUE TITLE
The font is too small, it seems ugly and difficult to read!

### ISSUE THREAD

**Issue by RyanOrigens** [stephenmk/Jitendex#64]
I like the furigana implementation, but the font size and tags seem too small. Additionally, the tags appear uneven in size compared to the other dictionaries.

Your Version of JMDICT (EXTRA)

![image](https://github.com/stephenmk/Jitendex/assets/103891807/a32b3842-abc1-4616-9fb9-1a7832e9bda1)

New Version

![image](https://github.com/stephenmk/Jitendex/assets/103891807/4a241984-ba66-431b-a88c-4b50660ceeab)

**Comment by parfait8566** [comment]
I had a similar issue with the font size. Not sure if it's just a personal preference or Windows makes the default settings look worse.
Anyway, this custom CSS fixed it for me:
```
[data-sc-code] {
  font-weight: normal !important;
  font-size: 1em !important;
}
[title="spelling and reading variants"] {
  font-weight: normal !important;
  font-size: 1em !important;
}
li[data-sc-content="example-sentence-a"] {
  font-size: 100% !important;
}
li[data-sc-content="example-sentence-b"] {
  font-size: 100% !important;
}
```

**Comment by bgs6** [comment]
You can increase the scale of the popup.

<details>
  <summary>Click to expand image</summary>

![image](https://github.com/stephenmk/Jitendex/assets/34460788/156a6a22-4ec4-42e0-bcea-15d0baa4e838)
</details>

Or if you are in the search page you can just zoom in.

The size is fine, and increasing it would make it too big compared to other dictionaries.

<details>
  <summary>Click to expand image</summary>

![image](https://github.com/stephenmk/Jitendex/assets/34460788/38faad30-d2a8-470e-81d8-63ed1fec4c34)
</details>

**Comment by RyanOrigens** [comment]
I use the native window rather than the pop up itself, and the spacing and furigana on top of the sentence seems quite odd too me and very difficult to read


JMDICT EXTRA

![image](https://github.com/stephenmk/Jitendex/assets/103891807/f7a2d491-d8ee-47ce-9c31-e00102a307f1)

Jitendex

![image](https://github.com/stephenmk/Jitendex/assets/103891807/2a756f4e-a371-4969-b9b1-58a47b78cb84)

**Comment by RyanOrigens** [comment]
[bgs6](https://github.com/bgs6) Did you change anything? it seems good...

**Comment by bgs6** [comment]
> [bgs6](https://github.com/bgs6) Did you change anything? it seems good...

I only changed the scale to 125% as shown in the pic above. You could increase it even more if it's still too small for you.

**Comment by RyanOrigens** [comment]
[parfait8566](https://github.com/parfait8566) it worked out, thank you.

**Comment by RyanOrigens** [comment]
I still think the defaults should be improved, so i'll leave it open.
