### ISSUE TITLE
Suggestion/question regarding the default red font color

### ISSUE THREAD

**Issue by yuswritescode** [stephenmk/Jitendex#66]
The current default red font is difficult to look at when used in combination with dark mode. I created a custom CSS style through the wiki page (only changed font color to orange and removed the source links), but I noticed that my custom CSS style is only applied to the popup, whereas I was hoping that these changes would also apply to the created Anki card, which turns out with the uncomfortable default red font and also with the source links.

Is there a way to apply the custom CSS style also to an Anki card? If not, what about using a simple black/white (depending on whether the user is using dark/light mode) underline while keeping the target word in the same font color as the rest of the sentence? Imo, using a certain color as the default color has a higher risk to make people uncomfortable.

**Comment by stephenmk** [comment]
Any custom CSS that you can use in Yomitan can also be used in Anki. I'm planning to add another wiki page soon with the instructions. Here's a [youtube video](https://www.youtube.com/watch?v=F1j1Zx0mXME) with some examples.

I think I might replace the red font with emphasis marks (black circles or sesame dots). This is traditionally how emphasis is added in [Japanese typography](https://en.wikipedia.org/wiki/Emphasis_mark).

<table>
<tr><th>Black Circles</th><th>Sesame Dots</th></tr>
<tr>
<td><img src='https://github.com/stephenmk/Jitendex/assets/8003332/c5d406a6-f362-4451-afe3-173774628208'/></td>
<td><img src='https://github.com/stephenmk/Jitendex/assets/8003332/7cc5cbc6-6718-4730-98d4-6e3b12cd3606'/></td>

</tr>
</table>

**Comment by stephenmk** [comment]
Turns out there's actually a dedicated CSS style ([text-emphasis](https://developer.mozilla.org/en-US/docs/Web/CSS/text-emphasis) for producing these emphasis marks. It's not supported by Yomitan at the moment but I can get the same effect by using ruby text.

At the moment I like the way that red dots look.

![red_dots](https://github.com/stephenmk/Jitendex/assets/8003332/89199f38-2def-4032-a544-0efa47430706)

**Comment by yuswritescode** [comment]
> Turns out there's actually a dedicated CSS style ([text-emphasis](https://developer.mozilla.org/en-US/docs/Web/CSS/text-emphasis)) for producing these emphasis marks. It's not supported by Yomitan at the moment but I can get the same effect by using ruby text.
> 
> At the moment I like the way that red dots look.
> 
> ![red_dots](https://private-user-images.githubusercontent.com/8003332/300156184-89199f38-2def-4032-a544-0efa47430706.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNjQ2MTIsIm5iZiI6MTcwNjM2NDMxMiwicGF0aCI6Ii84MDAzMzMyLzMwMDE1NjE4NC04OTE5OWYzOC0yZGVmLTQwMzItYTU0NC0wZWZhNDc0MzA3MDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjdUMTQwNTEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTQ3NjBhMTlkYWZhZjU5ZmZmNDViNjdiMjM4ZmZiY2I5OGM2ZTIyYjIyZTk2ZDcxNDY0N2MyZTVhZWYzZDAxMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.eNHxy_0zSebxqi14LTnLw2piTG9kenATqS2NKfRhj_k)

Hi Stephen, thank you for your reply and ideas! Imho, the one with the red dots looks the most convenient; the red dots allow us to quickly locate the target word (whether we are using dark or light mode) while the target word remains in the same font color as the rest of the sentence, which shouldn't cause inconvience whether we are reading in dark or light mode. Personally, I like it as a default option.

Thank you for the Youtube video and the wiki page, I will keep playing around with the settings. 

Have a nice day.

**Comment by yuswritescode** [comment]
Hi Stephen, I got a question out of curiosity regarding the Custom CSS. I have tried to change the font color of the target word in Jitendex through the Custom CSS screen. When the popup shows up, the target word in the example sentence is indeed shown with an orange font color. However, when I create an Anki card through that popup, the font color reverts back to the default red one in the Anki card (the sentence with the target word in orange below, is the sentence that I have mined). The removed source links also appear in the Anki card. Have I missed a step, or is this working as intended? 

![1](https://github.com/stephenmk/Jitendex/assets/110858019/891b5848-fe6f-4007-bc8f-5180f8fe857d)
![2](https://github.com/stephenmk/Jitendex/assets/110858019/91310db0-ff6d-41dd-80a8-339c30ee36b8)
![3](https://github.com/stephenmk/Jitendex/assets/110858019/0a19747a-943f-48c7-8359-56cb43562a1a)

**Comment by stephenmk** [comment]
I just published [a new version of Jitendex](https://github.com/stephenmk/Jitendex/releases/latest) which uses those red dots instead of red fonts to highlight the example sentence keywords.

To customize styles in Anki, you first need to open the card browser. There should be a button on this screen labeled "Cards...".

![cards](https://github.com/stephenmk/Jitendex/assets/8003332/f1b2e26d-2a5c-4844-9152-f68654db7022)

When you click on the "Cards..." button, it will open a new window. You need to click the "Styling" button in this window. Then you can paste the custom styles into the textbox below it.

![styles](https://github.com/stephenmk/Jitendex/assets/8003332/de58a118-c127-428b-9ab5-691ab2520fb3)

**Comment by yuswritescode** [comment]
Sorry for my very late reply. Thank you so much for taking your time and effort to write a clear and kind explanation, really appreciated. It is working as you have explained. Thank you again!
