### ISSUE TITLE
Yomitan Anki integration not working properly?

### ISSUE THREAD

**Issue by KuruKuru3532** [stephenmk/Jitendex#7]
Just to preface, I'm not entirely sure how handlebars work, and this might just be a case of me not knowing what I'm doing.

Whenever I add a term from [Yomitan](https://github.com/themoeway/yomitan) to Anki, the glossary field just returns: 

> "⭐Jitendex [2023-10-21][object Object]"

without the definition appended at all. Do I have to change something in the card template for it to work properly?

![image](https://github.com/stephenmk/Jitendex/assets/32959775/ac504162-a021-410a-ba84-1cc9f027c587)

**Comment by stephenmk** [comment]
Yomitan isn't recommended for general usage at the moment. It's still being tested by its developers. See [the note](https://github.com/themoeway/yomitan#yomitan) in their readme:

> Important note: Yomitan is still not recommended for use, as we are still trying to complete the transition to Manifest V3 (which is required of all new browser extensions), and there are [some critical bugs remaining](https://github.com/themoeway/yomitan/issues?q=is%3Aopen+is%3Aissue+label%3Apriority%2Fhigh). This is also why there is no stable release of yomitan yet.

You might have better luck using [Yomibaba](https://github.com/forsakeninfinity/yomibaba) until Yomitan has an official release.

The default handlebars in Yomibaba work fine with Jitendex without any extra configuration. If you are using custom handlebars, you might want to open an issue in [arbyste's fork of JPMN](https://github.com/arbyste/jp-mining-note) if you're using some version of JPMN. I unfortunately don't know enough about handlebars to be able to help, but I'm confident that the problem isn't with this dictionary itself. I know there have been people who have had trouble getting Jitendex to work with their custom handlebars, but they were able to get it to work after fixing their setups.
