### ISSUE TITLE
Reevaluate presentation of sense restrictions

### ISSUE THREAD

**Issue by stephenmk** [stephenmk/Jitendex#76]
### Discussed in https://github.com/stephenmk/Jitendex/discussions/74

<div type='discussions-op-text'>

<sup>Originally posted by **parfait8566** February 10, 2024</sup>
For example, the entry "十戒" currently looks like this:

- 1st sense〔十戒 only〕
- 2nd sense

I think it would be immediately clearer if the restriction information was shown more like this:
- 1st sense 〔十戒〕
- 2nd sense〔十戒・十誡〕

I guess it could look awkward if there are a ton of possible forms/readings for the same sense, but wouldn't it be possible to make it that if they exceed a certain number they revert to the previous look?</div>

**Comment by stephenmk** [comment]
Hmm... it would be cool if I could integrate the sense restrictions into the forms table.

A couple mockups

![gunsei](https://github.com/user-attachments/assets/22f84aad-57a8-423a-b272-066088ab8556)
![jikkai](https://github.com/user-attachments/assets/f6e6164f-b707-44ca-8ce3-aab37ddc8650)

**Comment by parfait8566** [comment]
How would this work with e.g. a form that applies to multiple senses but not all?

I'm going to propose an edit for 十戒, as JMdict generally seems to be more partial to notes. I personally prefer restrictions, but I guess they're unpopular.
I still like the "system" I originally proposed, I think that some kokugos occasionally use something similar (like Meikyo for 群生).

**Comment by stephenmk** [comment]
> How would this work with e.g. a form that applies to multiple senses but not all?

Tell me if I'm crazy.

ばね left | ばね right
--- | ---
![bane2](https://github.com/user-attachments/assets/15e86514-74a3-4760-9129-9e85b345fa82) | ![bane](https://github.com/user-attachments/assets/7ff26e4e-21ce-4dea-8533-0e6469ca56fe)


じっかい top | じっかい bottom
--- | ---
![jikkai2](https://github.com/user-attachments/assets/b7f87b3a-9ac5-46f1-9705-53cf613795d6) | ![jikkai1](https://github.com/user-attachments/assets/287f7db6-4a24-4331-9101-7c5d00833819)

> I'm going to propose an edit for 十戒, as JMdict generally seems to be more partial to notes. 

That's the direction we're going in, and that's probably best for most apps that use jmdict data. It makes it difficult for me to do things that I think are cool, though.

**Comment by stephenmk** [comment]
The more I think about this setup, the more I like it. I think I'm gonna go ahead and implement it.

Sometimes the results will be a little difficult to understand, but I think that's only when the data itself is difficult to understand. For example, in the entry for よんど, ４°【しど】 doesn't technically apply to any of the senses. I think it's easier to see this through the table approach at least.

Before | After
--- | ---
![yondo2](https://github.com/user-attachments/assets/6cb30f5b-c63f-42c7-ac9b-38f4e36a6b97) | ![yondo](https://github.com/user-attachments/assets/ab023005-6bb4-4a47-a8a5-ead65df53123)

**Comment by parfait8566** [comment]
> Tell me if I'm crazy. I think I prefer right/bottom over left/top.
> ばね left 	ばね right
> ![bane2](https://private-user-images.githubusercontent.com/8003332/379401991-15e86514-74a3-4760-9129-9e85b345fa82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3MjE4MTMsIm5iZiI6MTcyOTcyMTUxMywicGF0aCI6Ii84MDAzMzMyLzM3OTQwMTk5MS0xNWU4NjUxNC03NGEzLTQ3NjAtOTEyOS05ZTg1YjM0NWZhODIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjNUMjIxMTUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDg2NWFhZTY3ZDU1NTY4MjI2ZmY0NzYyNThjMDc5Y2ZlOTRiMjA1YTFmOWE5ZTM4YzViNDIyMjAyYmQxYzg1NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.q8rHroOxIUh2kdYWaMEoCGDKUSdIt3Xc17ZjqIX8Ng0) 	![bane](https://private-user-images.githubusercontent.com/8003332/379402270-7ff26e4e-21ce-4dea-8533-0e6469ca56fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3MjE4MTMsIm5iZiI6MTcyOTcyMTUxMywicGF0aCI6Ii84MDAzMzMyLzM3OTQwMjI3MC03ZmYyNmU0ZS0yMWNlLTRkZWEtODUzMy0wZTY0NjljYTU2ZmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjNUMjIxMTUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2M3ZWFmOGNjNTIwNTBkNmJhZWJlNDM1NzU3YTg4YzM2ZGEyOTUxMjAxMmU3OGNkMzU4YWNkMGIyYmJkMTczOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.6xp_BOOZJuf-uClnVmtOlNv_imVuf5-1ALkXBmycNT8)
> じっかい top 	じっかい bottom
> ![jikkai2](https://private-user-images.githubusercontent.com/8003332/379401993-b7f87b3a-9ac5-46f1-9705-53cf613795d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3MjE4MTMsIm5iZiI6MTcyOTcyMTUxMywicGF0aCI6Ii84MDAzMzMyLzM3OTQwMTk5My1iN2Y4N2IzYS05YWM1LTQ2ZjEtOTcwNS01M2NmNjEzNzk1ZDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjNUMjIxMTUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2E3M2NiZjQ3YWUzNTAzMzA1NzI1NTg1N2NhZTk5YWY0NjNiMDljZTI4OTAwZGYxZTFkZTEyZTA4NjQxMTgwYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.cKePALid9lUX5RfSfN-IdY3Qk7Jz53Yhz_Rd4Gz1f8c) 	![jikkai1](https://private-user-images.githubusercontent.com/8003332/379402101-287f7db6-4a24-4331-9101-7c5d00833819.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3MjE4MTMsIm5iZiI6MTcyOTcyMTUxMywicGF0aCI6Ii84MDAzMzMyLzM3OTQwMjEwMS0yODdmN2RiNi00YTI0LTQzMzEtOTEwMS03YzVkMDA4MzM4MTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjNUMjIxMTUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjAzMmY5MzNiNTU5NzMwYWFmNDExMzYwNDI3ZDQyNzA4N2E4MzUzMTYyNjE4NTQ4N2Y3ZjhkMzdmM2EzOTUyNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.70D-Z9biroApe1Y9r7cAW2-1A_sCtsd7gFJTu9WVMRk)

That's actually pretty neat. I personally prefer right/top. Though with restrictions on the top the two empty rows on the left look a bit awkward.
 
> That's the direction we're going in, and that's probably best for most apps that use jmdict data. It makes it difficult for me to do things that I think are cool, though.

Wouldn't it be technically possible to systematically convert notes into normal restrictions? They usually follow the same format ("occ. written as", "also written as", etc.). Maybe too outlandish.

**Comment by stephenmk** [comment]
I ended up going with a left/top setup. If every sense applies to a given column or row, then I replaced the numbers with an asterisk.

Many entries with restrictions are just frustratingly complicated and should probably be split up in the source data.

![kusuburu](https://github.com/user-attachments/assets/77d85d99-d1ab-4a3b-b124-3c31f177f571)
![nurui](https://github.com/user-attachments/assets/3446a215-571b-4945-91ef-5b226b0c2cfb)
![debana](https://github.com/user-attachments/assets/5b04fcbf-718c-48e7-b2a7-866b7884ad68)
![naisho](https://github.com/user-attachments/assets/b9c9286c-8222-4b88-ad69-faaf24a3d039)
