### ISSUE TITLE
Use new yomitan definition format for redirections

### ISSUE THREAD

**Issue by StefanVukovic99** [stephenmk/Jitendex#78]
The search-only entries currently require a click to get redirected to the main entry. Maybe the new "dictionary deinflection" definition type can be used to redirect automatically.
![Screenshot from 2024-02-13 16-22-14](https://github.com/stephenmk/Jitendex/assets/24891609/85314d55-5dcf-4f13-81a0-86fb36ed5320)
![Screenshot from 2024-02-13 16-23-51](https://github.com/stephenmk/Jitendex/assets/24891609/b2998ce8-1d4e-4395-a59c-24e87cbae622)
Keeping the structured definition can allow users to opt out of the automatic redirect by toggling off  "Use deinflections" in the dictionary details on yomitan.

**Comment by stephenmk** [comment]
This won't be hard to do but I can't implement this feature until it's supported by all stable versions of Yomitan. I'm sure you're already aware of this, but I'm mentioning it for the sake of anyone else who might be wondering.

**Comment by StefanVukovic99** [comment]
Yomitan stable got new releases, so this should now work for everyone :muscle:

**Comment by stephenmk** [comment]
It takes a little while for Yomitan updates to [roll out to everyone](https://github.com/stephenmk/Jitendex/issues/44), so I didn't want to add this feature to the most recent version I published. I'm planning to include it with the next one.
