### ISSUE TITLE
Request for Guidance on Converting Arabic-Japanese Dictionary for Yomitan

### ISSUE THREAD

**Issue by FahadHeiji** [stephenmk/Jitendex#81]
Hi Stephen,

I hope you well. I have opened the question  [localization of Jitendex in Arabic](https://github.com/stephenmk/Jitendex/issues/39). I have found an Arabic-Japanese dictionary that I would like to convert for use in Yomitan.

I am seeking your guidance on how you converted the Jitendex dictionary to be compatible with Yomitan. Specifically, I would like to know how to structure the JSON file for the dictionary entries. Here is an example of the JSON structure I am currently working with:

```json
{
  "Word": {
    "Id": 1,
    "Kana": "あい",
    "Writings": [
      {
        "Text": "愛",
        "Class": 0,
        "Parts": [{ "Kanji": 24859, "Reading": "あい" }]
      }
    ],
    "JLPT": 3,
    "Difficulty": 5,
    "Meanings": [
      {
        "Arabic": "حُبّ، وِدّ، مَوَدَّة، مَحَبَّة، مَعزَّة، عِشْق، غَرَام، هَوَى، هُيَام، وَلَه، شَغَف (|بالقراءة|)، وَلَع (|بالفن|)؛",
        "Note": "",
        "Japanese": "そのものの価値を認め、強く引きつけられる気持。",
        "Source": "岩波国語辞典",
        "SentenceIds": [1220, 1601, 2632],
        "Pictures": [],
        "Related": []
      }
    ],
    "Categories": [
      { "Id": 9, "Name": "اسم", "ShortName": "" },
      {
        "Id": 26,
        "Name": "اسم يمكن استخدامه كفعل بإضافة する",
        "ShortName": ""
      }
    ]
  }
}
```

Could you provide a template or guidelines on how to structure this JSON file to be compatible with Yomitan? Any help or guidance would be greatly appreciated.

Thank you in advance for your time and assistance.

**Comment by stephenmk** [comment]
Rather than trying to explain all the details of how to convert it to a Yomitan-compatible format, it would probably be faster if you just send me the data. Is this data free and/or openly licensed (e.g. Creative Commons)?

**Comment by FahadHeiji** [comment]
Here's the thing, I have requested permission from the author to create a copy of the dictionary, as it is not openly licensed. Currently, I am awaiting the author's response.

Additionally, please note that the dictionary undergoes periodic updates. It would be impractical to ask for frequent data updates. As the saying goes, "Don't give me a fish every day, but teach me how to fish."
