### ISSUE TITLE
Add New Structured Content from Yomitan Update

### ISSUE THREAD

**Issue by sdavis175** [stephenmk/Jitendex#94]
Requesting an implementation of this new feature from Yomitan: https://github.com/themoeway/yomitan/pull/842 for the note boxes/sentence boxes/form tables, so that they can be toggled as a drop down.

**Comment by stephenmk** [comment]
I don't think this functionality is a good fit for the content in jitendex. If there is information in the dictionary entries that is worth hiding by default, most of the time I think it would probably be better to remove it altogether. I consider the note boxes / sentences / etc. to be as important as the definitions.

Entries may contain many of these info boxes, and to me it seems like a bad user experience to force users to click around so much to expand them.
